--- 
title: "Documentation for discoveryengine"
author: "Tarak Shah"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: tarakc02/discodocs
description: "Some documentation for the discoveryengine"
knit: "bookdown::render_book"
---

# Disco

Welcome to the introduction and extended documentation for the discoveryengine! The discoveryengine, also known as "Disco Engine" or just "Disco," is a tool enabling Prospect Development staff to do custom prospecting, written in the R programming language. Feel free to read this document in order, or to jump around or just bookmark it and refer to it as needed. You may find the search feature helpful, you can access it by clicking on the little magnifying glass at the top of the screen. 

## Help wanted

This site is a work in progress. One way you can help is to report any mistakes you find (typos, spelling mistakes, grammatical errors) or any areas that could be explained better (if something was not clear to you, there's a good chance it won't be clear to others either. Use the [Issues page](https://github.com/tarakc02/discodocs/issues) -- click on the green "New Issue" button and enter a short message explaining what's wrong. If you'd like to suggest edits directly, you can do so by clicking on the pen-and-paper icon at the top of any page on this site (guide coming soon). Thank you!
